### PR TITLE
Enable py312 builds

### PR DESCRIPTION
**Pull request by mrakitin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender

**Review by prjemian — APPROVED** [review]

**Comment by prjemian** [comment]
Is libhkl package limiting here?

**Comment by mrakitin** [comment]
Yes, I think we need a new release of `libhkl` including Python 3.12.

**Comment by prjemian** [comment]
I'll look into it.

**Comment by prjemian** [comment]
- https://github.com/conda-forge/hkl-feedstock/pull/16

**Comment by prjemian** [comment]
If addition of Py3.12 means a new release of libhkl itself, that may be delayed a bit.  I'm working on a branch right now and encountering some changes in the gobject-introspection tool chain that are challenging.  The [problem](https://github.com/bluesky/libhkl/issues/13) is that a draft version of the libhkl.so library works successfully in Python on debian buster but not on RHEL9.  It comes down to the version of the glib subproject that is selected by the gobject-introspection tag.

**Comment by prjemian** [comment]
```
2024-04-29T19:23:05.6186725Z Encountered problems while solving:
2024-04-29T19:23:05.6237740Z   - package hkl-5.0.0.2173-py310h7e962ad_6 requires python_abi 3.10.* *_cp310, but none of the providers can be installed
2024-04-29T19:23:05.6238290Z 
2024-04-29T19:23:05.6238657Z Could not solve for environment specs
2024-04-29T19:23:05.6239042Z The following packages are incompatible
2024-04-29T19:23:05.6242554Z ├─ hkl is installable with the potential options
2024-04-29T19:23:05.6243263Z │  ├─ hkl [5.0.0.2173|5.0.0.3001|5.0.0.3357] would require
2024-04-29T19:23:05.6243659Z │  │  └─ python_abi 3.10.* *_cp310, which can be installed;
2024-04-29T19:23:05.6244043Z │  ├─ hkl [5.0.0.2173|5.0.0.3001|5.0.0.3357] would require
2024-04-29T19:23:05.6244409Z │  │  └─ python_abi 3.11.* *_cp311, which can be installed;
2024-04-29T19:23:05.6244711Z │  ├─ hkl 5.0.0.2173 would require
2024-04-29T19:23:05.6245054Z │  │  └─ python_abi 3.6.* *_cp36m, which can be installed;
2024-04-29T19:23:05.6245361Z │  ├─ hkl 5.0.0.2173 would require
2024-04-29T19:23:05.6245702Z │  │  └─ python_abi 3.7.* *_cp37m, which can be installed;
2024-04-29T19:23:05.6245996Z │  ├─ hkl 5.0.0.2173 would require
2024-04-29T19:23:05.6246344Z │  │  └─ python_abi 3.8 *_pypy38_pp73, which can be installed;
2024-04-29T19:23:05.6247578Z │  ├─ hkl [5.0.0.2173|5.0.0.3001|5.0.0.3357] would require
2024-04-29T19:23:05.6248134Z │  │  └─ python_abi 3.8.* *_cp38, which can be installed;
2024-04-29T19:23:05.6248511Z │  ├─ hkl [5.0.0.2173|5.0.0.3001|5.0.0.3357] would require
2024-04-29T19:23:05.6248868Z │  │  └─ python_abi 3.9.* *_cp39, which can be installed;
2024-04-29T19:23:05.6249193Z │  └─ hkl 5.0.0.2173 would require
2024-04-29T19:23:05.6249524Z │     └─ python_abi 3.9 *_pypy39_pp73, which can be installed;
2024-04-29T19:23:05.6250050Z └─ python_abi 3.12.* *_cp312 is not installable because it conflicts with any installable versions previously reported.
```

**Comment by prjemian** [comment]
- https://github.com/conda-forge/hkl-feedstock/pull/16 did not add Py3.12
- https://github.com/conda-forge/hkl-feedstock/pull/17 needs to add Py3.12

**Comment by mrakitin** [comment]
This builds fine now for Python 3.12. I'll go ahead and merge this PR.

**Pull request merged**
