### PR TITLE
V1.1.0

### PR DESCRIPTION
**Pull request by prjemian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by prjemian** [comment]
@conda-forge-admin, please rerender

**Comment by prjemian** [comment]
```py
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/hklpy_1705100662038/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.11/site-packages/hkl/__init__.py", line 18, in <module>
    from setuptools_scm import get_version
ModuleNotFoundError: No module named 'setuptools_scm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/hklpy_1705100662038/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/hklpy_1705100662038/test_tmp/run_test.py", line 2, in <module>
    import hkl
  File "/home/conda/feedstock_root/build_artifacts/hklpy_1705100662038/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.11/site-packages/hkl/__init__.py", line 25, in <module>
    __version__ = version("pkgdemo")
                  ^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/hklpy_1705100662038/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.11/importlib/metadata/__init__.py", line 1008, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/hklpy_1705100662038/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/hklpy_1705100662038/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pkgdemo
WARNING: Tests failed for hklpy-1.1.0rc1-py311h38be061_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: hklpy-1.1.0rc1-py311h38be061_0.conda
##[error]Bash exited with code '1'.
Finishing: Run docker build
```

**Comment by prjemian** [comment]
https://conda-forge.org/docs/maintainer/knowledge_base.html#using-setuptools-scm

**Comment by prjemian** [comment]
Still, in [py311](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/858134/logs/16):

```py
2024-01-13T16:17:53.1998902Z export SRC_DIR=/home/conda/feedstock_root/build_artifacts/hklpy_1705162407790/test_tmp
2024-01-13T16:17:53.6251491Z import: 'hkl'
2024-01-13T16:17:53.6821810Z Traceback (most recent call last):
2024-01-13T16:17:53.6823635Z   File "/home/conda/feedstock_root/build_artifacts/hklpy_1705162407790/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.11/site-packages/hkl/__init__.py", line 18, in <module>
2024-01-13T16:17:53.6824523Z     from setuptools_scm import get_version
2024-01-13T16:17:53.6825095Z ModuleNotFoundError: No module named 'setuptools_scm'
```

**Comment by prjemian** [comment]
Not a failure of `setuptools_scm` but `importlib.metadata.PackageNotFoundError: No package metadata was found for pkgdemo`

**Review by mrakitin — APPROVED** [review]

**Pull request merged**
