### PR TITLE
Add `setuptools_scm` to properly report the version

### PR DESCRIPTION
**Pull request by mrakitin**
Currently, the reported version of the `hklpy` package is 0.0.0:

```bash
$ conda list | grep hkl
# packages in environment at .../hklpy311:
hkl                       5.0.0.3434      py311h38be061_0    conda-forge
hklpy                     0.0.0                    pypi_0    pypi
```

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender

**Comment by prjemian** [comment]
@mrakitin Thanks for this.  I've been noticing that the fallback to importlib.metadata does not report the version as expected.  Seems the MAJOR part has been stripped.

**Comment by mrakitin** [comment]
It's due to we switched from `setup.py` -> `pyproject.toml` and the versioneer is gone now. I've updated the description with the example.

**Comment by prjemian** [comment]
> It's due to we switched ...

The switch added a [fallback](https://github.com/bluesky/hklpy/blob/9c9e98e29ef6e6ec4f59e5a92eaced09e237a456/hkl/__init__.py#L19-L28) to `importlib.metadata.version` and that fallback is the root cause of the version not reported correctly now. Specifically these lines execute when `from setuptools_scm import get_version` raises an exception (is not available for import):

```py
    from importlib.metadata import version

    __version__ = version(PROJECT_NAME)
```

**Review by prjemian — APPROVED** [review]
LGTM

**Pull request merged**
